name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out the form below.

  - type: textarea
    id: feature-description
    attributes:
      label: 📝 Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve?
      placeholder: This feature would solve...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: How would you like this feature to work?
      placeholder: The feature should work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: I've also considered...

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 🔧 Estimated Complexity
      description: How complex do you think this feature is to implement?
      options:
        - Simple (few hours)
        - Medium (few days)
        - Complex (few weeks)
        - Very Complex (months)

  - type: checkboxes
    id: documentation-impact
    attributes:
      label: 📚 Documentation Impact
      description: What documentation will need to be updated?
      options:
        - label: README updates
        - label: API documentation
        - label: Architecture documentation
        - label: Deployment guide
        - label: User guide

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Additional information...

