name: Sync to Architecture Repository

on:
  push:
    branches: [main]
    paths:
      - 'SECURITY.md'

jobs:
  sync-to-architecture:
    name: Sync Template Changes to Architecture
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
    
    steps:
      - name: Checkout Template Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ARCHITECTURE_SYNC_TOKEN }}
      
      - name: Clone Architecture Repository
        run: |
          git clone https://x-access-token:${{ secrets.ARCHITECTURE_SYNC_TOKEN }}@github.com/${{ github.repository_owner }}/saas-ecosystem-architecture.git arch-repo
          cd arch-repo
          git config user.name "Template Sync Bot"
          git config user.email "template-sync@users.noreply.github.com"
          sync_branch="template-sync-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$sync_branch"
          echo "sync_branch=$sync_branch" >> $GITHUB_ENV
      
      - name: Sync SECURITY.md
        run: |
          echo "Syncing SECURITY.md..."
          
          if [ -f "arch-repo/SECURITY.md" ]; then
            echo "Found existing SECURITY.md"
            if grep -q "<!-- TEMPLATE_SECURITY_START -->" arch-repo/SECURITY.md; then
              echo "Removing existing template section..."
              perl -0pe 's/<!-- TEMPLATE_SECURITY_START -->.*?<!-- TEMPLATE_SECURITY_END -->//gs' arch-repo/SECURITY.md > arch-repo/SECURITY.md.clean
              mv arch-repo/SECURITY.md.clean arch-repo/SECURITY.md
            fi
          fi
          
          echo "" >> arch-repo/SECURITY.md
          echo "<!-- TEMPLATE_SECURITY_START -->" >> arch-repo/SECURITY.md
          echo "## Template Repository Security Standards" >> arch-repo/SECURITY.md
          echo "" >> arch-repo/SECURITY.md
          cat SECURITY.md >> arch-repo/SECURITY.md
          echo "" >> arch-repo/SECURITY.md
          echo "<!-- TEMPLATE_SECURITY_END -->" >> arch-repo/SECURITY.md
      
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
      
      - name: Commit and Create PR
        run: |
          cd arch-repo
          git add SECURITY.md
          
          if git diff --staged --quiet; then
            echo "No changes to sync"
            exit 0
          fi
          
          git commit -m "Sync SECURITY.md from template repository"
          git remote set-url origin https://x-access-token:${{ secrets.ARCHITECTURE_SYNC_TOKEN }}@github.com/${{ github.repository_owner }}/saas-ecosystem-architecture.git
          git push origin "$sync_branch"
          
          gh pr create \
            --repo "${{ github.repository_owner }}/saas-ecosystem-architecture" \
            --title "Sync SECURITY.md from template" \
            --body "Automated sync of SECURITY.md from template repository" \
            --head "$sync_branch" \
            --base "main"
        env:
          GH_TOKEN: ${{ secrets.ARCHITECTURE_SYNC_TOKEN }}