name: Test Sync Workflow

on:
  workflow_dispatch:

jobs:
  test-sync:
    name: Test Sync Configuration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ARCHITECTURE_SYNC_TOKEN }}
      
      - name: Test Token Access
        run: |
          echo "Testing authentication..."
          git clone https://x-access-token:${{ secrets.ARCHITECTURE_SYNC_TOKEN }}@github.com/${{ github.repository_owner }}/saas-ecosystem-architecture.git test-clone
          echo "✅ Successfully cloned architecture repository"
          ls -la test-clone/
          
      - name: Test GitHub CLI
        run: |
          echo "Installing GitHub CLI..."
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
          echo "✅ GitHub CLI installed successfully"
        env:
          GH_TOKEN: ${{ secrets.ARCHITECTURE_SYNC_TOKEN }}