name: Sync to Architecture Repository

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'scripts/**'
      - 'SECURITY.md'
      - 'jest.config.js'
      - 'playwright.config.ts'

jobs:
  sync-to-architecture:
    name: Sync Template Changes to Architecture
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
    
    steps:
      - name: Checkout Template Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Detect Changes
        id: changes
        run: |
          # Use proper before/after SHAs for multi-commit pushes
          if [ "${{ github.event_name }}" = "push" ]; then
            before_sha="${{ github.event.before }}"
            after_sha="${{ github.event.after }}"
            # Handle initial push case
            if [ "$before_sha" = "0000000000000000000000000000000000000000" ]; then
              changed_files=$(git diff --name-only HEAD~1 HEAD)
            else
              changed_files=$(git diff --name-only "$before_sha" "$after_sha")
            fi
          else
            # Fallback for other events
            changed_files=$(git diff --name-only origin/main...HEAD)
          fi
          
          echo "Changed files:"
          echo "$changed_files"
          
          security_changes=false
          ci_changes=false
          scripts_changes=false
          
          if echo "$changed_files" | grep -E "(SECURITY\.md|scripts/security-validation\.sh)"; then
            security_changes=true
          fi
          
          if echo "$changed_files" | grep -E "\.github/workflows/"; then
            ci_changes=true
          fi
          
          if echo "$changed_files" | grep -E "scripts/"; then
            scripts_changes=true
          fi
          
          echo "security_changes=$security_changes" >> $GITHUB_OUTPUT
          echo "ci_changes=$ci_changes" >> $GITHUB_OUTPUT
          echo "scripts_changes=$scripts_changes" >> $GITHUB_OUTPUT
          
          if [ "$security_changes" = "true" ] || [ "$ci_changes" = "true" ] || [ "$scripts_changes" = "true" ]; then
            echo "sync_needed=true" >> $GITHUB_OUTPUT
          else
            echo "sync_needed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Setup Git and Clone Architecture Repo
        if: steps.changes.outputs.sync_needed == 'true'
        run: |
          # Clone architecture repository with authentication
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/saas-ecosystem-architecture.git arch-repo
          cd arch-repo
          
          # Configure git
          git config user.name "Template Sync Bot"
          git config user.email "template-sync@users.noreply.github.com"
          
          # Create sync branch
          sync_branch="template-sync-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$sync_branch"
          echo "sync_branch=$sync_branch" >> $GITHUB_ENV
          
          cd ..
      
      - name: Sync Files
        if: steps.changes.outputs.sync_needed == 'true'
        run: |
          echo "🔄 Syncing files to architecture repository..."
          
          # Sync security improvements
          if [ "${{ steps.changes.outputs.security_changes }}" = "true" ]; then
            echo "🔐 Syncing security improvements..."
            if [ -f "scripts/security-validation.sh" ]; then
              cp scripts/security-validation.sh arch-repo/scripts/
              echo "✅ Security validation script synced"
            fi
            if [ -f "SECURITY.md" ]; then
              # Merge security content rather than overwrite
              if [ -f "arch-repo/SECURITY.md" ]; then
                echo "" >> arch-repo/SECURITY.md
                echo "## Updates from Template Repository" >> arch-repo/SECURITY.md
                echo "" >> arch-repo/SECURITY.md
                cat SECURITY.md >> arch-repo/SECURITY.md
              else
                cp SECURITY.md arch-repo/
              fi
              echo "✅ Security documentation synced"
            fi
          fi
          
          # Sync CI/workflow improvements
          if [ "${{ steps.changes.outputs.ci_changes }}" = "true" ]; then
            echo "🚀 Syncing CI improvements..."
            mkdir -p arch-repo/standards/workflows/templates/
            for workflow in .github/workflows/*.yml; do
              if [ -f "$workflow" ] && [ "$(basename "$workflow")" != "sync-architecture.yml" ]; then
                cp "$workflow" "arch-repo/standards/workflows/templates/$(basename "$workflow")"
                echo "✅ Synced workflow: $(basename "$workflow")"
              fi
            done
          fi
          
          # Sync script improvements
          if [ "${{ steps.changes.outputs.scripts_changes }}" = "true" ]; then
            echo "🛠️ Syncing script improvements..."
            for script in scripts/*.sh; do
              if [ -f "$script" ] && [ "$(basename "$script")" != "dev-setup.sh" ]; then
                cp "$script" "arch-repo/scripts/"
                echo "✅ Synced script: $(basename "$script")"
              fi
            done
          fi
      
      - name: Commit and Push Changes
        if: steps.changes.outputs.sync_needed == 'true'
        run: |
          cd arch-repo
          
          # Check if there are changes to commit
          git add .
          if git diff --staged --quiet; then
            echo "ℹ️ No changes to sync"
            exit 0
          fi
          
          # Commit changes
          commit_message="🔄 Sync improvements from template repository

Template commit: ${{ github.sha }}
Changes: Security=${{ steps.changes.outputs.security_changes }}, CI=${{ steps.changes.outputs.ci_changes }}, Scripts=${{ steps.changes.outputs.scripts_changes }}

Auto-synced by template→architecture workflow"
          
          git commit -m "$commit_message"
          
          # Push using GITHUB_TOKEN with proper authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/saas-ecosystem-architecture.git
          git push origin "$sync_branch"
          
          echo "✅ Changes pushed to branch: $sync_branch"
          
          # Create PR using GitHub CLI
          echo "📝 Creating pull request..."
          gh pr create \
            --repo "${{ github.repository_owner }}/saas-ecosystem-architecture" \
            --title "🔄 Sync improvements from template repository" \
            --body "## Template→Architecture Sync

**Source commit**: \`${{ github.sha }}\`
**Triggered by**: ${{ github.event.head_commit.message }}

### Changes Synced
- Security changes: ${{ steps.changes.outputs.security_changes }}
- CI changes: ${{ steps.changes.outputs.ci_changes }}
- Scripts changes: ${{ steps.changes.outputs.scripts_changes }}

### Review Checklist
- [ ] Security patterns are appropriate for architecture repo
- [ ] CI templates work with architecture structure  
- [ ] Scripts are compatible with architecture workflows
- [ ] Documentation standards are maintained

**Auto-generated by template sync workflow**" \
            --head "$sync_branch" \
            --base "main"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}